matrix:
  include:
    - language: csharp
    dist: xenial
    mono: none
    sudo: required
    dotnet: 2.2
    install:
    - cd enson-be
    - dotnet restore
    script:
    - dotnet build

    - language: node_js
    sudo: false
    node_js:
      - "stable"
    install:
    - cd enson-fe && npm install
    script:
    - npm test
    - npm run build

notifications:
  email: false

