matrix:
  include:
    - language: csharp
    dist: xenial
    mono: none
    sudo: required
    dotnet: 2.2
    install:
    - cd enson-be
    - dotnet restore
    script:
    - dotnet build

    - language: node_js
    dist: xenial
    sudo: false
    node_js:
      - 8
      - 10
    install:
    - cd enson-fe && npm install
    script:
    - npm run build
    deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: build
    on:
      branch: dev

notifications:
  email: false

